# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 144bd7a900033c22a418cf525a7b36fd5580dba770b5c3726e58c22f6269a4940f6a2aaf928d200e4d92729ee0f8f4e952b8b997e03ebacc2523b6e50c5ab719

test:
  secret_key_base: df4ea97c15ade4ece0c9be888608d835676b32f3baf66e772a07aed8fe543a248bb21bd31f08511b00f48fb72a53c7c0b6f27f30a618c74fbc66e739d048a09e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
